import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Porsche | Abner Alves",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-white" lang="PT-br">
      <body className={inter.className}>{children}</body>
      <link rel="shortcut icon" href="IconePorsche.png" type="image/x-icon" />
    </html>
  );
}
